# Arquivo: config.yaml

credentials:
  usernames:
    jsilva:
      email: j.silva@suagestora.com
      name: João Silva (Advisor)
      password: '12345' # Substitua pela senha criptografada
    aoliveira:
      email: a.oliveira@suagestora.com
      name: Ana Oliveira (Analista)
      password: '12345' # Substitua pela senha criptografada
cookie:
  expiry_days: 30
  key: 'alguma_chave_secreta_aleatoria' # Chave para o cookie de login
  name: pag_cookie
preauthorized:
  emails:
  - j.silva@suagestora.com
