# Arquivo: config.yaml
credentials:
  usernames:
    jsilva:
      email: j.silva@suagestora.com
      name: João Silva (Advisor)
      password: 'SENHA_HASHED_AQUI_1'
    aoliveira:
      email: a.oliveira@suagestora.com
      name: Ana Oliveira (Analista)
      password: 'SENHA_HASHED_AQUI_2'
cookie:
  expiry_days: 30
  key: 'chave_secreta_final_pag'
  name: pag_cookie
preauthorized:
  emails: []
